[package]
name = "netbattleship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_cbor = "*"
structopt = "*"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1