name: "Itch.io Build"
on:
  push:
    tags:
      - "*"

jobs:
  compile:
    name: "Compile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu
      - run: |
          mkdir out{,/linux,/linux-gui,/windows,/windows-gui}
          mv target/release/netbattleship out/linux
          mv target/release/netbattleship-gui out/linux-gui
          mv target/x86_64-pc-windows-gnu/release/netbattleship.exe out/windows
          mv target/x86_64-pc-windows-gnu/release/netbattleship-gui.exe out/windows-gui
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./out/linux
          itchUsername: handlewithcaregames
          itchGameId: netbattleship
          buildChannel: linux
          buildNumber: ${{ github.ref_name }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./out/linux-gui
          itchUsername: handlewithcaregames
          itchGameId: netbattleship
          buildChannel: linux-gui
          buildNumber: ${{ github.ref_name }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./out/windows
          itchUsername: handlewithcaregames
          itchGameId: netbattleship
          buildChannel: windows
          buildNumber: ${{ github.ref_name }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCHIO_DEPLOY}}
          gameData: ./out/windows-gui
          itchUsername: handlewithcaregames
          itchGameId: netbattleship
          buildChannel: windows-gui
          buildNumber: ${{ github.ref_name }}